-- SQL script to populate CreemProduct table with initial data
-- This should be saved as supabase/seed.sql

-- Make sure to replace placeholder 'creemId' and 'id' values for paid plans
-- with your actual Creem Product IDs.
-- For paid plans, 'id' should be a proper UUID generated by the database.

-- 1. Free Trial Product
INSERT INTO public."CreemProduct" (
    "id", "name", "description", "price", "currency", "creemId", "active",
    "plan_tier", "billing_period", "grants_credits", "display_credits_per_month",
    "interval", "interval_count", "is_popular", "features", "button_text",
    "createdAt", "updatedAt"
) VALUES (
    gen_random_uuid(), 'Free Trial', 'Get started with Flux Kontext and explore basic features.', 0.00, 'USD', 'flux_free_trial_v1', TRUE,
    'free_trial', 'one_time', 40, 0,
    NULL, NULL, FALSE, '["40 free credits", "Basic AI services access"]', 'Start Free Trial',
    NOW(), NOW()
)
ON CONFLICT ("creemId") DO UPDATE SET
    "name" = EXCLUDED."name",
    "description" = EXCLUDED."description",
    "price" = EXCLUDED."price",
    "currency" = EXCLUDED."currency",
    "active" = EXCLUDED."active",
    "plan_tier" = EXCLUDED."plan_tier",
    "billing_period" = EXCLUDED."billing_period",
    "grants_credits" = EXCLUDED."grants_credits",
    "display_credits_per_month" = EXCLUDED."display_credits_per_month",
    "interval" = EXCLUDED."interval",
    "interval_count" = EXCLUDED."interval_count",
    "is_popular" = EXCLUDED."is_popular",
    "features" = EXCLUDED."features",
    "button_text" = EXCLUDED."button_text",
    "updatedAt" = NOW();

-- 2. Starter Monthly Product
-- !!! REPLACE 'creem_starter_monthly_placeholder' with your actual Creem Product ID !!!
INSERT INTO public."CreemProduct" (
    "id", "name", "description", "price", "currency", "creemId", "active",
    "plan_tier", "billing_period", "grants_credits", "display_credits_per_month",
    "interval", "interval_count", "is_popular", "features", "button_text",
    "createdAt", "updatedAt"
) VALUES (
    gen_random_uuid(), 'Starter Monthly', 'Perfect for individuals and small projects.', 9.90, 'USD', 'prod_4Yp1aN1hIXfaZ6nmkhxX4r', TRUE,
    'starter', 'one_time', 800, 800,
    'month', 1, FALSE, '["800 credits per month", "Standard AI services", "Email support"]', 'Get Starter',
    NOW(), NOW()
)
ON CONFLICT ("creemId") DO UPDATE SET
    "name" = EXCLUDED."name",
    "description" = EXCLUDED."description",
    "price" = EXCLUDED."price",
    "currency" = EXCLUDED."currency",
    "active" = EXCLUDED."active",
    "plan_tier" = EXCLUDED."plan_tier",
    "billing_period" = EXCLUDED."billing_period",
    "grants_credits" = EXCLUDED."grants_credits",
    "display_credits_per_month" = EXCLUDED."display_credits_per_month",
    "interval" = EXCLUDED."interval",
    "interval_count" = EXCLUDED."interval_count",
    "is_popular" = EXCLUDED."is_popular",
    "features" = EXCLUDED."features",
    "button_text" = EXCLUDED."button_text",
    "updatedAt" = NOW();

-- 3. Standard Monthly Product
-- !!! REPLACE 'creem_standard_monthly_placeholder' with your actual Creem Product ID !!!
INSERT INTO public."CreemProduct" (
    "id", "name", "description", "price", "currency", "creemId", "active",
    "plan_tier", "billing_period", "grants_credits", "display_credits_per_month",
    "interval", "interval_count", "is_popular", "features", "button_text",
    "createdAt", "updatedAt"
) VALUES (
    gen_random_uuid(), 'Standard Monthly', 'Most popular choice for growing creators.', 19.90, 'USD', 'prod_5JuWWb8K7oLjx5nNuzO8tF', TRUE,
    'standard', 'one_time', 3000, 3000,
    'month', 1, TRUE, '["3000 credits per month", "Advanced AI services", "Priority email support"]', 'Get Standard',
    NOW(), NOW()
)
ON CONFLICT ("creemId") DO UPDATE SET
    "name" = EXCLUDED."name",
    "description" = EXCLUDED."description",
    "price" = EXCLUDED."price",
    "currency" = EXCLUDED."currency",
    "active" = EXCLUDED."active",
    "plan_tier" = EXCLUDED."plan_tier",
    "billing_period" = EXCLUDED."billing_period",
    "grants_credits" = EXCLUDED."grants_credits",
    "display_credits_per_month" = EXCLUDED."display_credits_per_month",
    "interval" = EXCLUDED."interval",
    "interval_count" = EXCLUDED."interval_count",
    "is_popular" = EXCLUDED."is_popular",
    "features" = EXCLUDED."features",
    "button_text" = EXCLUDED."button_text",
    "updatedAt" = NOW();

-- 4. Premium Monthly Product
-- !!! REPLACE 'creem_premium_monthly_placeholder' with your actual Creem Product ID !!!
INSERT INTO public."CreemProduct" (
    "id", "name", "description", "price", "currency", "creemId", "active",
    "plan_tier", "billing_period", "grants_credits", "display_credits_per_month",
    "interval", "interval_count", "is_popular", "features", "button_text",
    "createdAt", "updatedAt"
) VALUES (
    gen_random_uuid(), 'Premium Monthly', 'For power users and businesses requiring more.', 39.90, 'USD', 'prod_1KueImdLHARwEE4yVUAvOv', TRUE,
    'premium', 'one_time', 8000, 8000,
    'month', 1, FALSE, '["8000 credits per month", "All AI services", "Dedicated support"]', 'Get Premium',
    NOW(), NOW()
)
ON CONFLICT ("creemId") DO UPDATE SET
    "name" = EXCLUDED."name",
    "description" = EXCLUDED."description",
    "price" = EXCLUDED."price",
    "currency" = EXCLUDED."currency",
    "active" = EXCLUDED."active",
    "plan_tier" = EXCLUDED."plan_tier",
    "billing_period" = EXCLUDED."billing_period",
    "grants_credits" = EXCLUDED."grants_credits",
    "display_credits_per_month" = EXCLUDED."display_credits_per_month",
    "interval" = EXCLUDED."interval",
    "interval_count" = EXCLUDED."interval_count",
    "is_popular" = EXCLUDED."is_popular",
    "features" = EXCLUDED."features",
    "button_text" = EXCLUDED."button_text",
    "updatedAt" = NOW();

-- SELECT * FROM public."CreemProduct"; -- To verify the inserted data
-- Commenting out the SELECT for a seed file, as it's not typically needed for seeding.
